### ISSUE TITLE
TypeError: temp_override() takes no positional arguments

### ISSUE THREAD

**Issue by skittixch** [ranjian0/blender-vscode-dev#1]
I'm getting an error when I start blender from vscode via ctrl-shift-p

```python
Debug client attached.
TypeError: temp_override() takes no positional arguments

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CrayB\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-vscode-dev-main\watcher.py", line 41, in load_handler
    operator_with_context(
  File "C:\Users\CrayB\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-vscode-dev-main\utils.py", line 35, in operator_with_context
    with bpy.context.temp_override(context_override):
SystemError: <built-in method temp_override of Context object at 0x0000027F1E68BB40> returned a result with an exception set
```

**Comment by ranjian0** [comment]
Yeah, also noticed this error yesterday. Will fix it over the weekend!
